stages:
  - lint
  - test
  - deploy

variables:
  PYTHONPATH: "$CI_PROJECT_DIR"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python --version
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install pylint
    - pylint my_module/  # 🔧 sửa thành thư mục module Odoo thật sự
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

unit_test:
  stage: test
  script:
    - pip install pytest
    - pytest tests/
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

deploy_to_dev:
  stage: deploy
  script:
    - echo "Triển khai tới môi trường DEV tại server Odoo"
    # ví dụ: ssh hoặc rsync
    # - ssh user@your-server "cd /opt/odoo && git pull && systemctl restart odoo"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
